#!/usr/bin/env python3
"""Tests for vidconv.

    python3 -m unittest discover -s tests -v        # everything
    python3 -m unittest tests.test_vidconv.Safety   # just the destructive paths

Stdlib only, like vidconv itself -- there is no pytest here and there shouldn't
be one, since the project rule is that nothing gets installed.

Two layers:

  * Unit tests exercise the pure functions directly. No ffmpeg, instant.
  * Integration tests run the real script against real video generated by
    ffmpeg's lavfi sources. Slower, but the bugs this tool has actually had all
    lived in the seam between vidconv and ffmpeg -- an ffmpeg that exits 0
    having done nothing, an ffmpeg that refuses a job we then "clean up" -- and
    a mock would have happily reproduced our wrong assumptions instead of
    catching them.

The Safety class is the one that matters. Every test in it corresponds to a real
bug that reached a commit, and two of them destroyed a file before being found.
If you are about to relax one, read NOTES.md first.
"""

import contextlib
import importlib.util
import io
import os
import shutil
import subprocess
import sys
import tempfile
import time
import unittest
from importlib.machinery import SourceFileLoader
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCRIPT = REPO / "vidconv"


def load_vidconv():
    """Import vidconv as a module despite it having no .py extension."""
    loader = SourceFileLoader("vidconv", str(SCRIPT))
    spec = importlib.util.spec_from_loader("vidconv", loader)
    mod = importlib.util.module_from_spec(spec)
    # Must be in sys.modules *before* exec: @dataclasses.dataclass looks its class
    # up there while the class body is still executing, and fails if it's absent.
    sys.modules["vidconv"] = mod
    loader.exec_module(mod)  # safe: main() is behind an __name__ guard
    return mod


vc = load_vidconv()


CONFIG = """\
default_profile = "{profile}"

[paths]
source_dir = "{source_dir}"
output_dir = "{output_dir}"
flatten = {flatten}

[scan]
include = ["*.mkv"]

[ffmpeg]
overwrite_outputs = {overwrite_outputs}

[convert]
verify = "{verify_convert}"

[delete]
policy = "{policy}"
verify = "{verify_delete}"

[profiles.copy]
args = "-map 0 -c copy"
extension = ".mkv"

[profiles.x265]
args = "-map 0 -c:v libx265 -crf 30 -x265-params log-level=error -c:a copy"
extension = ".mkv"

[profiles.bogus]
args = "-map 0 -c:v definitely_not_an_encoder"
extension = ".mkv"
"""


class Base(unittest.TestCase):
    """Temp dir, a config writer, and a real-video generator."""

    @classmethod
    def setUpClass(cls):
        if not shutil.which("ffmpeg") or not shutil.which("ffprobe"):
            raise unittest.SkipTest("ffmpeg/ffprobe not on PATH")
        # Generate the fixture video once for the whole class and copy it per
        # test. Encoding is only ~0.15s, but tests copy it many times over.
        cls._fixture_dir = Path(tempfile.mkdtemp(prefix="vidconv-fixture-"))
        cls._fixture = cls._fixture_dir / "fixture.mkv"
        subprocess.run(
            ["ffmpeg", "-v", "error", "-y",
             "-f", "lavfi", "-i", "testsrc=duration=3:size=320x240:rate=10",
             "-f", "lavfi", "-i", "sine=duration=3",
             "-c:v", "libx264", "-c:a", "aac", str(cls._fixture)],
            check=True,
        )

    @classmethod
    def tearDownClass(cls):
        shutil.rmtree(cls._fixture_dir, ignore_errors=True)

    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="vidconv-test-"))
        self.addCleanup(shutil.rmtree, self.tmp, True)
        self.src = self.tmp / "src"
        self.out = self.tmp / "out"

    def video(self, relpath: str) -> Path:
        """Place a real 3s video at src/<relpath>."""
        dst = self.src / relpath
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(self._fixture, dst)
        return dst

    def config(self, **kw) -> Path:
        opts = dict(
            profile="copy",
            source_dir=str(self.src),
            output_dir=str(self.out),
            flatten="false",
            overwrite_outputs="false",
            verify_convert="probe",
            policy="never",
            verify_delete="decode",
        )
        opts.update(kw)
        path = self.tmp / "vidconv.toml"
        path.write_text(CONFIG.format(**opts))
        return path

    def run_vidconv(self, *args, config: Path | None = None):
        cfg = config or self.config()
        return subprocess.run(
            [sys.executable, str(SCRIPT), "--config", str(cfg), *args],
            capture_output=True, text=True, timeout=300,
        )

    # -- assertions ------------------------------------------------------------

    def assertDecodesTo(self, path: Path, seconds: float, delta: float = 0.5):
        """Assert the file really decodes to ~seconds.

        Deliberately not an ffprobe duration check: Matroska keeps duration in
        the segment header, so a truncated file still claims its full length.
        Only the decoded timestamp tells the truth. See NOTES.md.
        """
        got, err = vc.decode_duration(path)
        self.assertIsNotNone(got, f"{path} did not decode at all: {err}")
        self.assertAlmostEqual(got, seconds, delta=delta,
                               msg=f"{path} decoded to {got}s, expected ~{seconds}s")


class Units(Base):
    """Pure functions. No ffmpeg."""

    def test_output_path_mirrors_the_source_tree(self):
        cfg = vc.load_config(self.config())
        src = self.src / "Show" / "Season 1" / "ep one.mkv"
        dst = vc.output_path_for(src, cfg, cfg.profiles["copy"])
        self.assertEqual(dst, self.out / "Show" / "Season 1" / "ep one.mkv")

    def test_flatten_drops_the_subdirectories(self):
        cfg = vc.load_config(self.config(flatten="true"))
        src = self.src / "Show" / "Season 1" / "ep one.mkv"
        dst = vc.output_path_for(src, cfg, cfg.profiles["copy"])
        self.assertEqual(dst, self.out / "ep one.mkv")

    def test_is_same_file_sees_through_symlinks_and_dotdot(self):
        self.src.mkdir(parents=True)
        real = self.video("a.mkv")
        link = self.tmp / "link.mkv"
        link.symlink_to(real)
        dotdot = self.src / ".." / "src" / "a.mkv"

        self.assertTrue(vc.is_same_file(real, real))
        self.assertTrue(vc.is_same_file(real, link))
        self.assertTrue(vc.is_same_file(real, dotdot))
        # The common case: dst does not exist yet. Must not raise.
        self.assertFalse(vc.is_same_file(real, self.out / "a.mkv"))

    def test_file_identity_detects_a_rewrite_without_consulting_the_clock(self):
        self.src.mkdir(parents=True)
        f = self.src / "a.bin"
        self.assertIsNone(vc.file_identity(f))

        f.write_bytes(b"one")
        first = vc.file_identity(f)
        self.assertEqual(vc.file_identity(f), first, "unchanged file looked changed")

        f.write_bytes(b"two different")
        self.assertNotEqual(vc.file_identity(f), first)

        # Same length, so only the timestamp can give it away -- hence mtime_ns
        # rather than mtime, which a fast rewrite can land inside a single tick of.
        f.write_bytes(b"two_different")
        self.assertNotEqual(vc.file_identity(f), first)

    def test_verify_rank_is_ordered_weakest_to_strongest(self):
        self.assertLess(vc.VERIFY_RANK["none"], vc.VERIFY_RANK["probe"])
        self.assertLess(vc.VERIFY_RANK["probe"], vc.VERIFY_RANK["decode"])


class ConfigErrors(Base):
    """Bad configs must be rejected, not tolerated."""

    def assertRejected(self, needle: str, **kw):
        with self.assertRaises(vc.ConfigError) as caught:
            vc.load_config(self.config(**kw))
        self.assertIn(needle, str(caught.exception).lower())

    def test_same_source_and_output_dir_is_rejected(self):
        self.assertRejected("different", output_dir=str(self.src))

    def test_same_dir_spelled_via_dotdot_is_rejected(self):
        # Config-level equality has to compare resolved paths, or the check is
        # trivially defeated by spelling the same directory a second way.
        self.assertRejected("different", output_dir=str(self.src / ".." / "src"))

    def test_same_dir_via_symlink_is_rejected(self):
        self.src.mkdir(parents=True)
        link = self.tmp / "alias"
        link.symlink_to(self.src)
        self.assertRejected("different", output_dir=str(link))

    def test_renamed_overwrite_key_is_an_error_not_a_silent_default(self):
        # Ignoring it would turn a stale `overwrite = true` into false without a
        # word, i.e. the opposite of what the config plainly says.
        path = self.config()
        path.write_text(path.read_text().replace(
            "overwrite_outputs = false", "overwrite = true"))
        with self.assertRaises(vc.ConfigError) as caught:
            vc.load_config(path)
        self.assertIn("overwrite_outputs", str(caught.exception))

    def test_bad_verify_mode_is_rejected(self):
        self.assertRejected("delete.verify", verify_delete="sorta")
        self.assertRejected("convert.verify", verify_convert="sorta")

    def test_bad_delete_policy_is_rejected(self):
        self.assertRejected("delete.policy", policy="maybe")

    def test_config_error_exits_2(self):
        proc = self.run_vidconv("list", config=self.config(policy="maybe"))
        self.assertEqual(proc.returncode, 2)


class Convert(Base):
    """The happy paths."""

    def test_convert_mirrors_tree_and_leaves_sources_alone(self):
        self.video("Show/Season 1/ep one.mkv")
        self.video("Show/Season 1/ep two.mkv")

        proc = self.run_vidconv("convert")
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)

        # Filenames with spaces are in the fixtures on purpose: the shell scripts
        # this replaced mangled them.
        self.assertDecodesTo(self.out / "Show/Season 1/ep one.mkv", 3.0)
        self.assertDecodesTo(self.out / "Show/Season 1/ep two.mkv", 3.0)
        self.assertTrue((self.src / "Show/Season 1/ep one.mkv").is_file())

    def test_rerunning_skips_finished_work(self):
        self.video("a.mkv")
        self.run_vidconv("convert")
        proc = self.run_vidconv("convert")
        self.assertIn("nothing to convert", proc.stdout)

    def test_really_transcodes_when_the_profile_says_to(self):
        self.video("a.mkv")
        proc = self.run_vidconv("convert", "-p", "x265")
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
        codec = subprocess.run(
            ["ffprobe", "-v", "error", "-select_streams", "v:0",
             "-show_entries", "stream=codec_name", "-of", "csv=p=0",
             str(self.out / "a.mkv")],
            capture_output=True, text=True).stdout.strip()
        self.assertEqual(codec, "hevc")

    def test_overwrite_outputs_controls_only_the_y_flag(self):
        self.video("a.mkv")
        off = self.run_vidconv("convert", "--dry-run",
                               config=self.config(overwrite_outputs="false"))
        on = self.run_vidconv("convert", "--dry-run",
                              config=self.config(overwrite_outputs="true"))
        self.assertIn("-stats -n", off.stdout)
        self.assertIn("-stats -y", on.stdout)

    def test_nested_output_dir_is_not_rescanned_as_a_source(self):
        # output_dir inside source_dir is a layout people reach for. Outputs match
        # the include globs, so without the scan skipping the output tree the next
        # run would re-encode its own work forever.
        self.video("a.mkv")
        cfg = self.config(output_dir=str(self.src / "converted"))
        self.run_vidconv("convert", config=cfg)
        proc = self.run_vidconv("list", config=cfg)
        self.assertIn("1 file(s)", proc.stdout)

    def test_failed_encode_leaves_no_partial_output(self):
        # A corpse in output_dir looks like finished work to the next run and to
        # `clean`, which would then happily delete the source.
        self.video("a.mkv")
        proc = self.run_vidconv("convert", "-p", "bogus")
        self.assertEqual(proc.returncode, 1)
        self.assertFalse((self.out / "a.mkv").exists())
        self.assertTrue((self.src / "a.mkv").is_file())


class Safety(Base):
    """Destructive paths. Every test here is a bug that actually happened.

    Two of these destroyed a real file before the guard existed. Do not weaken
    one to make a refactor pass -- read NOTES.md and fix the refactor.
    """

    def test_truncated_output_never_authorises_deletion(self):
        # THE bug. Matroska stores duration in the segment header, so a truncated
        # file still claims its full runtime; ffprobe passes it and a full decode
        # exits 0 (early EOF reads as a clean end of stream). Only comparing how
        # far the decode actually got catches it. This was the exact hole in the
        # old remove.sh.
        self.video("a.mkv")
        self.run_vidconv("convert")
        out = self.out / "a.mkv"
        out.write_bytes(out.read_bytes()[: out.stat().st_size // 2])

        proc = self.run_vidconv("clean", "--delete", "auto")
        self.assertTrue((self.src / "a.mkv").is_file(),
                        "source deleted despite a truncated output")
        self.assertIn("output is short", proc.stdout)

    def test_empty_output_never_authorises_deletion(self):
        self.video("a.mkv")
        self.run_vidconv("convert")
        (self.out / "a.mkv").write_bytes(b"")

        self.run_vidconv("clean", "--delete", "auto")
        self.assertTrue((self.src / "a.mkv").is_file())

    def test_missing_output_never_authorises_deletion(self):
        self.video("a.mkv")
        self.run_vidconv("convert")
        (self.out / "a.mkv").unlink()

        self.run_vidconv("clean", "--delete", "auto")
        self.assertTrue((self.src / "a.mkv").is_file())

    def test_delete_verify_none_still_floors_at_probe(self):
        # Deleting on zero evidence is indefensible, so "none" is not honoured
        # here even though it is a legal value for [convert] verify.
        self.video("a.mkv")
        cfg = self.config(verify_delete="none")
        self.run_vidconv("convert", config=cfg)
        (self.out / "a.mkv").write_bytes(b"")

        self.run_vidconv("clean", "--delete", "auto", config=cfg)
        self.assertTrue((self.src / "a.mkv").is_file())

    def test_skipping_the_convert_check_cannot_skip_the_delete_check(self):
        # --verify none is a speed knob. It must never become a safety knob: a run
        # that deletes escalates the post-encode check to what deletion demands.
        self.video("a.mkv")
        proc = self.run_vidconv("convert", "--verify", "none", "--delete", "auto")
        self.assertIn("decode", proc.stdout,
                      "deleting run did not escalate to the decode check")
        self.assertFalse((self.src / "a.mkv").exists())
        self.assertDecodesTo(self.out / "a.mkv", 3.0)

    def test_no_op_is_caught_even_when_the_output_mtime_is_in_the_future(self):
        # The no-op guard used to compare dst's mtime against time.time(). On an SMB
        # or NFS share the mtime comes from the SERVER's clock while time.time() is
        # ours, so a NAS running fast would let a stale output pass as freshly
        # written, and a NAS running slow would fail every good conversion. The guard
        # now compares dst against its own prior state, so no clock is involved. A
        # future mtime is the cheap way to simulate a server clock running ahead.
        #
        # convert_one is called directly because `convert` skips files whose output
        # already exists, so it would never reach the guard. -n with an existing dst
        # is exactly the no-op this protects against: ffmpeg declines to clobber,
        # prints "already exists", and exits 0.
        src = self.video("a.mkv")
        cfg = vc.load_config(self.config())
        dst = self.out / "a.mkv"
        dst.parent.mkdir(parents=True)
        shutil.copy(src, dst)  # a valid, intact, but STALE output
        future = time.time() + 86400
        os.utime(dst, (future, future))
        stale = vc.file_identity(dst)

        with contextlib.redirect_stdout(io.StringIO()) as out:
            ok = vc.convert_one(src, dst, cfg.profiles["copy"], cfg, "probe",
                                overwrite=False)

        self.assertEqual(vc.file_identity(dst), stale, "test bug: dst was rewritten")
        self.assertFalse(ok, "a no-op encode was reported as a successful conversion")
        self.assertIn("did not write the output", out.getvalue())

    def test_redo_actually_re_encodes(self):
        # --redo was a silent no-op: under -n ffmpeg declines to clobber the
        # output, prints "already exists" and exits 0. convert_one then verified
        # the STALE output, passed, reported success -- and with --delete auto
        # removed the source having re-encoded nothing. It ate a real file.
        self.video("a.mkv")
        self.run_vidconv("convert")
        before = (self.out / "a.mkv").stat().st_mtime_ns

        proc = self.run_vidconv("convert", "--redo")
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
        self.assertGreater((self.out / "a.mkv").stat().st_mtime_ns, before,
                           "--redo reported success without rewriting the output")

    def test_source_is_never_its_own_output(self):
        # The one that got away. ffmpeg REFUSES to encode a file onto itself
        # ("Output same as Input") and exits non-zero -- which is our failed-encode
        # path, and that unlinks the partial output. When dst == src the "partial
        # output" is the source: ffmpeg protected the file and vidconv deleted it.
        #
        # load_config rejects this config outright, so the run never starts.
        self.video("a.mkv")
        cfg = self.config(output_dir=str(self.src))

        proc = self.run_vidconv("convert", "--redo", config=cfg)
        self.assertEqual(proc.returncode, 2)
        self.assertTrue((self.src / "a.mkv").is_file(), "vidconv deleted the source")
        self.assertDecodesTo(self.src / "a.mkv", 3.0)

    def test_convert_one_refuses_a_dst_that_is_the_src(self):
        # Belt and braces behind the config check, and the guard that actually
        # protects unlink(): config checks reason about directories, but hardlinks
        # and symlinks make two unequal paths the same file.
        src = self.video("a.mkv")
        cfg = vc.load_config(self.config())
        alias = self.tmp / "alias.mkv"
        alias.symlink_to(src)

        with contextlib.redirect_stdout(io.StringIO()) as out:
            ok = vc.convert_one(src, alias, cfg.profiles["copy"], cfg, "probe")
        self.assertFalse(ok)
        self.assertIn("refusing", out.getvalue())
        self.assertTrue(src.is_file(), "the source was deleted as a 'partial output'")
        self.assertDecodesTo(src, 3.0)

    def test_delete_auto_removes_sources_only_after_they_verify(self):
        self.video("keep me.mkv")
        self.video("me too.mkv")

        proc = self.run_vidconv("convert", "--delete", "auto")
        self.assertEqual(proc.returncode, 0, proc.stdout + proc.stderr)
        self.assertEqual(list(self.src.rglob("*.mkv")), [])
        self.assertDecodesTo(self.out / "keep me.mkv", 3.0)
        self.assertDecodesTo(self.out / "me too.mkv", 3.0)


if __name__ == "__main__":
    unittest.main(verbosity=2)
